name: Go
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.22" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test driver file
        working-directory: ./driver/file
        run: |
          go mod tidy
          go test -v -coverprofile=coverage.out ./...

      - name: Upload driver file coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./driver/file/coverage.out
          fail_ci_if_error: true
          verbose: true
          flags: file
          codecov_yml_path: ./.codecov.yml